{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mohamed-mar-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.releaseName }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
