apiVersion: v1
kind: Service
metadata:
  name: {{ include "mohamed-mar-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mohamed-mar-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.releaseName }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
